[package]
name = "chat"
version = "0.1.0"
authors = ["ryanking13 <def6488@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mio = "0.5"
http-muncher = "0.2.0"
rustc-serialize = "0.3.15"
sha1 = "0.1.1"
